services:
  postgres:
    image: postgres:17.2-alpine
    stdin_open: true
    tty: true
    restart: always
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
volumes:
  db_data:
